name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Verificar contenido antes de mover
        run: ls -R  # ✅ Verifica si la carpeta web/ está presente

      - name: Guardar la carpeta web antes de cambiar de rama
        run: mv web /tmp/web  # ✅ Guarda `web/` temporalmente

      - name: Publicar la carpeta web/ en la rama gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          mv /tmp/web/* ./  # ✅ Recupera la carpeta `web/`
          git add .
          git commit -m "Desplegando frontend a GitHub Pages"
          git push --force origin gh-pages
